### ISSUE TITLE
Error installing app

### ISSUE THREAD

**Issue by pentmo** [Blatzar/shiro-app#8]
I get this error upon trying to install this app:

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
	at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(lambda)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by AbdullahM0hamed** [comment]
The error is thrown at https://github.com/Aefyr/SAI/blob/46093b4e7ff9a317c2710fb5a31ea7784f3b5d87/app/src/main/java/com/aefyr/sai/model/filedescriptor/ContentUriFileDescriptor.java#L30 if the `DocumentFile.getName` is null (https://developer.android.com/reference/kotlin/androidx/documentfile/provider/DocumentFile#getName()) - very strange that you get that, what was the file named when you clicked it?

**Comment by Blatzar** [comment]
Closing due to inactivity and lack of information/replicability
